[build]
command = 'hugo'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.117.0'

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'

DefaultContentLanguage = "en"
[languages]
  [languages.en]
    title = "My New Hugo i18n Site"
    languageName = "English"
    weight = 1
  [languages.ru]
    title = "Мой сайт"
    languageName = "Russian"
    weight = 2